name: Github actions workflow
on: workflow_dispatch
jobs:
   first-job:
     runs-on: self-hosted
     steps:
       - name: welcome
         run: echo "github actions demo"
       - name: bye
         run: echo "demo complete"
