name: Github actions workflow
on: workflow_dispatch
jobs:
   first-job:
     runs-on: windows-runner
     steps:
       - name: welcome
         run: echo "github actions demo"
       - name: bye
         run: echo "demo complete"
